### ISSUE TITLE
Error generating video

### ISSUE THREAD

**Issue by adzcai** [ndrwmlnk/critic-guided-segmentation-of-rewarding-objects-in-first-person-views#2]
Amazing work! I was trying to replicate this model and training goes fine, but it throws this error when I try to generate the video via `python main.py -test --model output --output-video video_output`:

```
AttributeError: module 'pydensecrf.densecrf' has no attribute 'densecrf'
```

This is being run in a conda environment that's been initialized via the instructions. It also doesn't look like this function actually exists in the [`pydensecrf`](https://github.com/lucasb-eyer/pydensecrf) library. Would it be possible to address this? Thanks for your time!

**Comment by augustinharter** [comment]
Hi,
thanks for your interest and pointing out the problem. I just pushed some changes, which I hope fix the issue for you.
Let me know! :)
